version: "3.7"

services:
  proxy:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: python-app
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    labels:
      traefik.http.routers.flask.rule: PathPrefix(`/api`)
      traefik.http.middlewares.strip-api.stripprefix.prefixes: /api
      traefik.http.services.flask.loadbalancer.server.port: 5000
      traefik.http.routers.flask.middlewares: strip-api@docker
      

  react-client:
    image: vtcs2304s19/blabber-client
    labels:
      traefik.http.routers.react.rule: PathPrefix(`/`)
      traefik.http.services.react.loadbalancer.server.port: 80